import { IPlan } from "@/shared/components/molecules/cards/Plan/types"

export const carersPlans: Array<IPlan> = [
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Design UX/UI", "Programação"],
    off: "70% OFF",
    title: "Carreira de Desenvolvedor UX/UI",
    courses: ["Design UX/UI", "Design UX/UI Avançado", "HTML e CSS"],
    workload: "36 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 17.940",
    totalPrice: "R$ 1.614",
    monthlyPrice: "R$ 135",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Design UX/UI"],
    off: "70% OFF",
    title: "Carreira de Designer UX/UI",
    courses: ["Design UX/UI", "Design UX/UI Avançado"],
    workload: "24 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 14.580",
    totalPrice: "R$ 972",
    monthlyPrice: "R$ 81",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Design UX/UI", "Programação", "Produto"],
    off: "70% OFF",
    title: "Carreira de Web Product Manager",
    courses: ["Product Management", "Design UX/UI", "HTML e CSS"],
    workload: "35 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 17.760",
    totalPrice: "R$ 1.598",
    monthlyPrice: "R$ 133",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Design UX/UI", "Produto"],
    off: "70% OFF",
    title: "Carreira de Product Designer",
    courses: ["Product Management", "Design UX/UI"],
    workload: "23 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 11.460",
    totalPrice: "R$ 1.031",
    monthlyPrice: "R$ 86",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Design UX/UI", "Programação"],
    off: "70% OFF",
    title: "Carreira de Full Stack Designer",
    courses: [
      "Design UX/UI",
      "HTML e CSS",
      "Javascript",
      "React JS",
      "Back End",
    ],
    workload: "64 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 37.050",
    totalPrice: "R$ 3.334",
    monthlyPrice: "R$ 278",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Design UX/UI"],
    off: "70% OFF",
    title: "Carreira de Designer UX/UI + Figma",
    courses: ["Design UX/UI", "Figma", "Design UX/UI Avançado"],
    workload: "32 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 23.626",
    totalPrice: "R$ 2.126",
    monthlyPrice: "R$ 177",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Programação"],
    off: "70% OFF",
    title: "Carreira de Desenvolvedor Front-End React JS",
    courses: ["HTML e CSS", "Javascript", "React JS"],
    workload: "27 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 17.430",
    totalPrice: "R$ 1.568",
    monthlyPrice: "R$ 131",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Programação"],
    off: "70% OFF",
    title: "Carreira de Desenvolvedor Full Stack",
    courses: ["HTML e CSS", "Javascript", "React JS", "Back End"],
    workload: "51 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 31.710",
    totalPrice: "R$ 2.853",
    monthlyPrice: "R$ 238",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Programação"],
    off: "70% OFF",
    title: "Carreira de Desenvolvedor Back End",
    courses: ["Javascript", "SQL", "Back End"],
    workload: "45 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 27.090",
    totalPrice: "R$ 2.438",
    monthlyPrice: "R$ 203",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Programação", "Data"],
    off: "70% OFF",
    title: "Carreira de Desenvolvedor Full Stack Python",
    courses: ["HTML e CSS", "Javascript", "React JS", "Back End", "Python"],
    workload: "61 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 36.480",
    totalPrice: "R$ 3.283",
    monthlyPrice: "R$ 274",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Programação"],
    off: "70% OFF",
    title: "Carreira de Programador Iniciante + Mentorias",
    courses: ["HTML e CSS", "Javascript"],
    workload: "20 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 12.836",
    totalPrice: "R$ 1.155",
    monthlyPrice: "R$ 96",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Produto"],
    off: "70% OFF",
    title: "Carreira de Product Manager",
    courses: ["Product Management", "Product Management Avançado"],
    workload: "20 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 15.646",
    totalPrice: "R$ 1.408",
    monthlyPrice: "R$ 117",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Data"],
    off: "70% OFF",
    title: "Carreira de Cientista de dados",
    courses: ["Data Analytics", "Data Science"],
    workload: "39 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 17.356",
    totalPrice: "R$ 1.562",
    monthlyPrice: "R$ 130",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Data"],
    off: "70% OFF",
    title: "Carreira de Cientista de dados + Python",
    courses: ["Data Analytics", "Python", "Data Science"],
    workload: "49 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 22.126",
    totalPrice: "R$ 1.991",
    monthlyPrice: "R$ 166",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Data"],
    off: "70% OFF",
    title: "Carreira de Introdução a dados",
    courses: ["Excel e Google Sheets", "Power BI"],
    workload: "11 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 9.106",
    totalPrice: "R$ 819",
    monthlyPrice: "R$ 68",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Data"],
    off: "70% OFF",
    title: "Carreira de Analista de dados",
    courses: ["Excel e Google Sheets", "Power BI", "Data Analytics", "SQL"],
    workload: "36 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 22.530",
    totalPrice: "R$ 2.027",
    monthlyPrice: "R$ 169",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Data"],
    off: "70% OFF",
    title: "Carreira de Analista de dados Python",
    courses: [
      "Excel e Google Sheets",
      "Power BI",
      "Data Analytics",
      "SQL",
      "Python",
    ],
    workload: "46 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 27.300",
    totalPrice: "R$ 2.457",
    monthlyPrice: "R$ 205",
  },
]

export const coursesPlans: Array<IPlan> = [
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Design UX/UI"],
    off: "70% OFF",
    title: "Design UX/UI Avançado",
    tag: "Online e ao vivo",
    workload: "11 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 9.750",
    totalPrice: "R$ 877",
    monthlyPrice: "R$ 73",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Design UX/UI"],
    off: "70% OFF",
    title: "Design UX/UI",
    tag: "Online e ao vivo",
    workload: "13 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 8.250",
    totalPrice: "R$ 742",
    monthlyPrice: "R$ 62",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Design UX/UI"],
    off: "70% OFF",
    title: "Figma",
    tag: "Online e ao vivo",
    workload: "8 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 8.250",
    totalPrice: "R$ 742",
    monthlyPrice: "R$ 62",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Marketing Digital"],
    off: "70% OFF",
    title: "Growth Marketing",
    tag: "Online e ao vivo",
    workload: "8 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 7.200",
    totalPrice: "R$ 648",
    monthlyPrice: "R$ 54",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Marketing Digital"],
    off: "70% OFF",
    title: "Estratégia e Gestão de Social Media",
    tag: "Online e ao vivo",
    workload: "11 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 6.433",
    totalPrice: "R$ 579",
    monthlyPrice: "R$ 48",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Programação"],
    off: "70% OFF",
    title: "Javascript",
    tag: "Online e ao vivo",
    workload: "8 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 6.500",
    totalPrice: "R$ 585",
    monthlyPrice: "R$ 49",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Programação"],
    off: "70% OFF",
    title: "React JS",
    tag: "Online e ao vivo",
    workload: "7 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 5.867",
    totalPrice: "R$ 528",
    monthlyPrice: "R$ 44",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Programação"],
    off: "70% OFF",
    title: "Back End",
    tag: "Online e ao vivo",
    workload: "24 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 15.867",
    totalPrice: "R$ 1.428",
    monthlyPrice: "R$ 119",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Programação"],
    off: "70% OFF",
    title: "HTML e CSS",
    tag: "Online e ao vivo",
    workload: "12 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 7.000",
    totalPrice: "R$ 630",
    monthlyPrice: "R$ 53",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Produto"],
    off: "70% OFF",
    title: "Product Management",
    tag: "Online e ao vivo",
    workload: "10 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 6.800",
    totalPrice: "R$ 612",
    monthlyPrice: "R$ 51",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Produto"],
    off: "70% OFF",
    title: "Product Management Avançado",
    tag: "Online e ao vivo",
    workload: "10 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 10.583",
    totalPrice: "R$ 952",
    monthlyPrice: "R$ 79",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Data"],
    off: "70% OFF",
    title: "Data Analytics",
    tag: "Online e ao vivo",
    workload: "12 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 7.183",
    totalPrice: "R$ 646",
    monthlyPrice: "R$ 54",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Data"],
    off: "70% OFF",
    title: "SQL",
    tag: "Online e ao vivo",
    workload: "13 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 7.733",
    totalPrice: "R$ 696",
    monthlyPrice: "R$ 58",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Data"],
    off: "70% OFF",
    title: "Data Science",
    tag: "Online e ao vivo",
    workload: "27 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 12.100",
    totalPrice: "R$ 1.089",
    monthlyPrice: "R$ 91",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Data"],
    off: "70% OFF",
    title: "Python",
    tag: "Online e ao vivo",
    workload: "10 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 5.300",
    totalPrice: "R$ 477",
    monthlyPrice: "R$ 40",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Data"],
    off: "70% OFF",
    title: "Power BI",
    tag: "Online e ao vivo",
    workload: "6 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 4.533",
    totalPrice: "R$ 408",
    monthlyPrice: "R$ 34",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Data"],
    off: "70% OFF",
    title: "Excel e Google Sheets",
    tag: "Online e ao vivo",
    workload: "5 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 5.583",
    totalPrice: "R$ 502",
    monthlyPrice: "R$ 42",
  },
  {
    header: "English Academy",
    type: ["Inglês"],
    off: "70% OFF",
    title: "Inglês para o mundo digital - Nível Elementary",
    tag: "Online e ao vivo",
    workload: "12 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 9.083",
    totalPrice: "R$ 817",
    monthlyPrice: "R$ 68",
  },
  {
    header: "English Academy",
    type: ["Inglês"],
    off: "70% OFF",
    title: "Inglês para o mundo digital - Nível Intermediate",
    tag: "Online e ao vivo",
    workload: "12 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 9.083",
    totalPrice: "R$ 817",
    monthlyPrice: "R$ 68",
  },
  {
    header: "Aproveite a Coderbolsa de 70%",
    type: ["Inteligencia Artificial"],
    off: "70% OFF",
    title: "Fundamentos de Inteligência Artificial",
    tag: "Modalidade CoderFlex",
    workload: "6 semanas / 2 aulas semanais de 2 h",
    standardPlan: "R$ 4.167",
    totalPrice: "R$ 375",
    monthlyPrice: "R$ 31",
  },
]
